// src/utils/indexList.js

export const INDEX_LIST = [
  "NIFTY 50",
  "BANKNIFTY",
  "FINNIFTY",
  "MIDCAPNIFTY",
  "NIFTY IT",
  "NIFTY AUTO",
  "NIFTY PHARMA",
  "NIFTY METAL",
  "NIFTY FMCG",
  "NIFTY PSU BANK",
  "NIFTY ENERGY",
  "NIFTY REALTY",
  "SENSEX",
];

export const STOCK_LIST = [
  "3MINDIA","ABBOTINDIA","AARTIDRUGS","AARTIIND","ABB","ABCAPITAL","ABFRL","ACC",
  "ADANIENT","ADANIPORTS","ADANIGREEN","ADANIPOWER","AJANTPHARM","AKZOINDIA",
  "ALKEM","AMARAJABAT","AMBUJACEM","APLLTD","APOLLOHOSP","APOLLOTYRE","ASHOKLEY",
  "ASIANPAINT","ASTRAL","ATUL","AUBANK","AUROPHARMA","AXISBANK","BAJAJFINSV",
  "BAJFINANCE","BANDHANBNK","BANKBARODA","BANKINDIA","BERGEPAINT","BHARATFORG",
  "BHARTIARTL","BHEL","BIOCON","BOSCHLTD","BPCL","BRITANNIA","CADILAHC","CANBK",
  "CHOLAFIN","CIPLA","COALINDIA","COFORGE","COLPAL","CONCOR","CUMMINSIND","DABUR",
  "DALBHARAT","DEEPAKNTR","DIVISLAB","DLF","DRREDDY","EICHERMOT","ESCORTS","EXIDEIND",
  "FEDERALBNK","GAIL","GODREJCP","GRANULES","GRASIM","GUJGASLTD","HAL","HAVELLS",
  "HCLTECH","HDFC","HDFCBANK","HDFCLIFE","HEROMOTOCO","HINDALCO","HINDPETRO",
  "HINDUNILVR","IEX","IGL","INDIGO","INDUSINDBK","INDUSTOWER","INFY","IOC","IRCTC",
  "ITC","JINDALSTEL","JSWSTEEL","JUBLFOOD","KOTAKBANK","L&TFH","LT","LUPIN","M&M",
  "MARICO","MARUTI","MCDOWELL-N","MFSL","MINDTREE","MUTHOOTFIN","NAUKRI","NESTLEIND",
  "NMDC","NTPC","ONGC","PAGEIND","PETRONET","PIIND","PNB","POWERGRID","RELIANCE",
  "SAIL","SBILIFE","SBIN","SHREECEM","SIEMENS","SRF","SRTRANSFIN","SUNPHARMA",
  "TATACHEM","TATACONSUM","TATAMOTORS","TATASTEEL","TCS","TECHM","TITAN","TORNTPOWER",
  "ULTRACEMCO","UPL","VOLTAS","WIPRO","ZEEL"
];
